### ISSUE TITLE
App starts to become heavy after one or more scratches

### ISSUE THREAD

**Issue by joaomagfreitas** [vintage/scratcher#1] opened 2019-07-26 22:15 UTC
Hi @vintage ! 

First of all, thank you very much for creating this plugin and publishing it! If I'm not wrong it's the first Flutter plugin that allows the scratch of an image :)

I'm integrating the plugin in the app I'm currently working on, which requires the scratch of images in a table (3 x 3 matrix). After scratching one image the app starts to become heavy, which results in low performance when scratching other images. `ScratchAccuracy.low` is already being used for each `Scratcher` widget, what can be done to increase the performance?

Cheers,
freitzzz

**Comment by vintage** [comment] 2019-07-26 22:44
Hey @freitzzz - the matrix 3x3 have been also used in the example app https://github.com/vintage/scratcher/tree/master/example - does it also slows down the performance for you? I didnt notice perf problems, but am eager to investigate if required.

**Comment by joaomagfreitas** [comment] 2019-07-27 10:52
> Hey @freitzzz - the matrix 3x3 have been also used in the example app https://github.com/vintage/scratcher/tree/master/example - does it also slows down the performance for you? I didnt notice perf problems, but am eager to investigate if required.

will test it in a bit and will give feedback!

**Comment by joaomagfreitas** [comment] 2019-07-27 11:07
@vintage Just tested it, and it also slows down the performance. Recorded a little video so you can see the performance decay.

Also, both tests were performed in a Samsung A300-F with Android 5.0.2 (Version 21)

https://youtu.be/kMTCpM3IhSk

**Comment by vintage** [comment] 2019-07-27 15:51
@freitzzz Thanks for the detailed info. Hope that all issues reported in projects are done like that! :) I've investigated the problem with profiler and found the root cause of it. Could you please install scratcher directly from Github to check if it solves the problem completely (or at least if there is an improvement)?

Just in case - https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by joaomagfreitas** [comment] 2019-07-27 18:01
Good afternoon @vintage,

I'm glad you liked my bug report :D I just tested the updated version of scratcher in the `example` app and also in my app, and in both apps the performance increased! Thank you so much for the fast fix and release :)

Here's a video using the 08793e660a39ee428b017a96149c8c59aae3be65 commit version of the example app

https://youtu.be/yTWanLOTsmE

**Comment by vintage** [comment] 2019-07-27 18:16
Awesome, looks much smoother now 🎉 Will release new version to pub.dev tomorrow evening so you wont need to depend on github repo anymore 🙃

**Comment by vintage** [comment] 2019-07-28 09:26
@freitzzz Version 1.1.0 just landed on the https://pub.dev/packages/scratcher Closing the issue 🎉

**Closed as completed by vintage** 2019-07-28 09:26 UTC
Labels: bug

**Comment by khalifa007** [comment] 2020-05-16 00:35
Can you please open a bug cus its come again !  slows down the performance in the begining.
