### ISSUE TITLE
Painting error if user keep their finger on scratching interface for some time

### ISSUE THREAD

**Issue by nooralibutt** [vintage/scratcher#22] opened 2021-02-23 14:45 UTC
Crashing if user keep their finger on scratching interface for some time

Here is screenshot of code where error is with my simulator screen

<img width="1680" alt="Screenshot 2021-02-23 at 7 41 09 PM" src="https://user-images.githubusercontent.com/6607146/108860003-9d440600-760f-11eb-8641-8de1c129ef4a.png">

**Comment by vintage** [comment] 2021-02-24 13:17
@nooralibutt how long is the "some time"? Will try to reproduce the issue locally and debug the root cause of it.

**Comment by nooralibutt** [comment] 2021-02-24 14:23
hardly 1 to 2 seconds

**Comment by vintage** [comment] 2021-03-05 13:37
Issue has been fixed in `1.4.2` release.

**Closed as completed by vintage** 2021-03-05 13:37 UTC
Labels: bug
