### ISSUE TITLE
Can tracks appear automatically?

### ISSUE THREAD

**Issue by lizhuoyuan** [vintage/scratcher#57] opened 2024-03-07 06:14 UTC
I hope that I can call a method, and then the track will automatically appear (simulating finger sliding), and then all will be displayed

**Comment by vintage** [comment] 2024-07-10 12:15
Duplicate of https://github.com/vintage/scratcher/issues/45

**Closed as completed by vintage** 2024-07-10 12:15 UTC

**Comment by programmerElephant** [comment] 2024-12-13 06:39
> 我希望可以调用一个方法，然后轨道会自动出现（模拟手指滑动），然后全部显示出来

did you solved it ?
